# Introducción a tensorflow

### Instalar tensofrlow

In [1]:
%pip install tensorflow[and-cuda]

Note: you may need to restart the kernel to use updated packages.


### Importar tensorflow

In [2]:
import tensorflow as tf

2025-01-09 17:37:39.288251: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-09 17:37:39.300830: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1736462259.316178  117297 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1736462259.320910  117297 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-09 17:37:39.337027: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

### Tensores

In [3]:
# Compute some values using a Tensor
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
print(c)
print(d)



tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [0. 1.]], shape=(2, 2), dtype=float32)


I0000 00:00:1736462262.104036  117297 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4143 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


### Operaciones básicas con tensores

In [4]:
import tensorflow as tf

# Crear tensores
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)
tensor_b = tf.constant([4, 5, 6], dtype=tf.float32)

# Operaciones básicas
suma = tf.add(tensor_a, tensor_b)
multiplicacion = tf.multiply(tensor_a, tensor_b)
promedio = tf.reduce_mean(tensor_a)

print("Suma:", suma.numpy())  # [5. 7. 9.]
print("Multiplicación:", multiplicacion.numpy())  # [4. 10. 18.]
print("Promedio:", promedio.numpy())  # 2.0


Suma: [5. 7. 9.]
Multiplicación: [ 4. 10. 18.]
Promedio: 2.0


In [5]:
suma

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

### Operaciones avanzadas con tensores

In [6]:
# Crear tensores con valores iniciales
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Calcular transpuesta
transpuesta = tf.transpose(x)

# Producto de matrices
matriz_a = tf.constant([[1, 2], [3, 4]])
matriz_b = tf.constant([[5, 6], [7, 8]])
producto_matrices = tf.matmul(matriz_a, matriz_b)

print("Transpuesta:\n", transpuesta.numpy())
print("Producto de Matrices:\n", producto_matrices.numpy())


Transpuesta:
 [[1. 3.]
 [2. 4.]]
Producto de Matrices:
 [[19 22]
 [43 50]]


In [7]:
producto_matrices

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

### Ejemplo de modelo básico con tensorflow

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Datos de entrenamiento
x_train = np.array([1, 2, 3, 4, 5], dtype=np.float32)
y_train = np.array([3, 5, 7, 9, 11], dtype=np.float32)  # y = 2x + 1

# Construcción del modelo
model = Sequential([
    Dense(units=1, input_shape=[1])  # Una capa con una neurona
])

# Compilación del modelo
model.compile(optimizer='sgd', loss='mean_squared_error')

# Entrenamiento
model.fit(x_train, y_train, epochs=500, verbose=0)


/home/tuteggito/Downloads/big data/material/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1736462262.957794  117501 service.cc:148] XLA service 0x702124003db0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1736462262.957817  117501 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 3060 Laptop GPU, Compute Capability 8.6
I0000 00:00:1736462262.981812  117501 cuda_dnn.cc:529] Loaded cuDNN version 90300
I0000 00:00:1736462263.097989  117501 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


In [9]:
# Predicción
prediccion = model.predict(np.array([6], dtype=np.float32))
print("Predicción para x=6:", prediccion[0][0])  # Aproximadamente 13

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
Predicción para x=6: 13.010897
